# # Starter pipeline

# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

trigger:
  branches:
    include:
      - develop
      # - master
  paths:
    include:
      - myngapp/*
pool:
  vmImage: "ubuntu-latest"
variables:
  containerRegistry: 'bitmesh acr'
  kubernetes_prod: 'Bitkube_prod'
  kubernetes_test: 'Bitkube_dev'
stages:
  - template: deploy-ngapp.yml
    parameters:
      name: myngapp
      serviceName: myngapp

